
// Pure JS list of your vibe-coded ripps.
// Each entry corresponds to a module at /Ripps/<id>.js that exports { meta, init(api), update(api,t,dt) }
export default [
  { id: 'kaleidoscope-mandelbrot-tumble-1', name: 'kaleidoscope-mandelbrot-tumble-1' },
  { id: 'kaleidoscope-newton-1', name: 'kaleidoscope-newton-1' },
  //{ id: 'cymatics-chaldni', name: 'cymatics-chaldni' },
  //{ id: 'cymatics-chaldni-1', name: 'cymatics-chaldni-1' },
  { id: 'kaleidoscope-newton', name: 'kaleidoscope-newton' },
  { id: 'kaleidoscope-newton-1', name: 'kaleidoscope-newton-1' },
  { id: 'kaleidoscope-prism-2-bilateral', name: 'kaleidoscope-prism-2-bilateral'},
  { id: 'kaleidoscope-prism-2', name: 'kaleidoscope-prism-2'},
  { id: 'kaleidoscope-mandelbrot-tumble-1', name: 'kaleidoscope-mandelbrot-tumble-1' },
  { id: 'kaleidoscope-wavefrontInterference-1', name: 'kaleidoscope-wavefrontInterference-1' },
  { id: 'kaleidoscope-caustic-malachite-1', name: 'kaleidoscope-caustic-malachite-1' },
  { id: 'kaleidoscope-caustic-organic-1', name: 'kaleidoscope-caustic-organic-1'},
  { id: 'oscilloscope-1', name: 'oscilloscope-1' },
  { id: 'cymatics-1', name: 'cymatics-1' },
  { id: 'curl-noise-submerged-1', name: 'curl-noise-submerged-1' },
  { id: 'curl-noise-aquatic-2', name: 'curl-noise-aquatic-2' },
  { id: 'curl-noise-aquatic-1', name: 'curl-noise-aquatic-1' },
  { id: 'caustic-smoke-2', name: 'caustic-smoke-2' },
  { id: 'caustic-smoke-1', name: 'caustic-smoke-1' },
  { id: 'jets-1', name: 'jets-1' },
  { id: 'spatters-1', name: 'spatters-1' },
  { id: 'vortex-1', name: 'vortex-1' },
  { id: 'fizz-1', name: 'fizz-1' },
  { id: 'cascade-1', name: 'cascade-1' },
  { id: 'tsunami-1', name: 'tsunami-1' },
  { id: 'rising-tide-1', name: 'rising-tide-1' },
  //{ id: 'circle-bands', name: 'circle-bands' },
  //{ id: 'oscilloscope-base', name: 'oscilloscope-base' },
  //{ id: 'sea-horizon-gradient', name: 'sea-horizon-gradient — 10s loop' },
  //{ id: 'sea-horizon', name: 'Sea Horizon — 10s loop' },
  //{ id: 'sea-horizon-gradient-2', name: 'sea-horizon-gradient-2 — 10s loop' },
  //{ id: 'sea-horizon-brand', name: 'sea-horizon-gradient-brand' },
  //{ id: 'sea-horizon-gradient-3', name: 'sea-horizon-gradient-3 — 10s loop' },
  //{ id: 't_wave-3', name: 't_wave-3' },
  //{ id: 't_wave-4', name: 't_wave-4' },
  //{ id: 't_wave-9', name: 't_wave-9' },
  //{ id: 't_wave-10', name: 't_wave-10' },
  //{ id: 't_wave-8', name: 't_wave-8' },
  //{ id: 't_wave-11', name: 't_wave-11' },
  //{ id: 't_wave-12', name: 't_wave-12' },
  //{ id: 'temari-1', name: 'temari-1' },
  //{ id: 'temari-2', name: 'temari-2' },
  //{ id: '7-up', name: '7-Up' },
  //{ id: '7-up-2', name: '7-Up' },
  //{ id: '7-up-3', name: '7-Up-3' },
  //{ id: 'raindrops-1', name: 'raindrops-1' },
  //{ id: 'raindrops-2', name: 'raindrops-2' },
  //{ id: 'raindrops-3', name: 'raindrops-3' },
  //{ id: 'raindrops-7', name: 'vapor-paint' },
  //{ id: 'raindrops-8', name: 'brand-paint' },
  //{ id: 'raindrops-6', name: '8bit volcano' },
  //{ id: 'raindrops-4', name: 'lava-matrix' },
  //{ id: 'raindrops-5', name: 'raindrops-5' },
  //{ id: 'candyorb-1', name: 'SMPTE-10hz-dreamMachine' },
  
  
];
